version: 1.0.0+1
name: log
description: A package with error handlers and logger.
publish_to: none

resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0

dev_dependencies:
  dart_code_metrics_presets: ^2.21.0
  test: ^1.25.15
