version: 1.0.0+1
name: app
description: A cross-platform app built with drift.
publish_to: none

resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  drift: ^2.25.1
  drift_flutter: ^0.2.4
  flutter:
    sdk: flutter
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.15
  dart_code_metrics_presets: ^2.21.0
  drift_dev: ^2.25.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  disable-swift-package-manager: true
  uses-material-design: true
