swagger_parser:
  client_postfix: Http
  default_content_type: "application/json"
  enums_parent_prefix: true
  enums_to_json: false
  export_file: true
  json_serializer: dart_mappable
  mark_files_as_generated: true
  original_http_response: true
  output_directory: lib/src
  unknown_enum_value: true
  path_method_name: false
  put_clients_in_folder: true
  root_client: false
  put_in_folder: true
  schema_path: schema/openapi.json

  replacement_rules:
    - pattern: "Object0"
      replacement: "SelectItem"
