# This configures how `build_runner` and associated builders should behave.
# For more information, see https://pub.dev/packages/build_config

targets:
  $default:
    # Reducing sources makes the build slightly faster (some of these are required
    # to exist in the default target).
    sources:
      - lib/**
      - web/**
      - "tool/**"
      - pubspec.yaml
      - lib/$lib$
      - $package$
    builders:
      auto_route_generator:auto_route_generator:
        options:
          generate_for:
            - lib/presentation/pages/**.dart
      auto_route_generator:auto_router_generator:
        options:
          generate_for:
            - lib/router/app_router.dart
