version: 1.0.0+1
name: app
description: A cross-platform app built with drift and dio.
publish_to: none

resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  auto_route: ^10.0.1
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  infinite_scroll_pagination: ^5.0.0
  intl: ^0.20.2
  log:
    path: ../packages/logger
  material_symbols_icons: ^4.2808.0
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.2
  rest_api:
    path: ../packages/rest_api
  world_countries: ^3.2.0

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  dart_code_metrics_presets: ^2.21.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  disable-swift-package-manager: true
  uses-material-design: true
  assets:
    - assets/fonts/

  fonts: # https://github.com/material-foundation/flutter-packages/issues/35
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
