name: verify_app

on:
  push:
    branches: [main]
    paths:
      - "flutter_app/**"
  pull_request:
    branches: [main]
    paths:
      - "flutter_app/**"
      - ".github/workflows/verify_app.yaml"

jobs:
  verify-app:
    name: Verify App
    uses: ./.github/workflows/verify_workflow.yaml
    with:
      name: flutter_app
    secrets: inherit
